version: '3'

services:

  pandoc:
    build:
      context: ./
      dockerfile: docker/Dockerfile-pandoc
    expose:
      - 80
    ports:
      - "8081:80"

    hostname: pandoc
    domainname: example.com

    restart: unless-stopped
    privileged: true
    stdin_open: false
    tty: false

  livepoll:
    build:
      context: ./
      dockerfile: docker/Dockerfile-livepoll
    expose:
      - 80
    ports:
      - "8082:3000"

    hostname: livepoll
    domainname: example.com

    restart: unless-stopped
    privileged: true
    stdin_open: false
    tty: false

    environment:
      LIVEPOLL_USE_INSECURE_HTTP: true

