version: '3'

services:

  pandoc:
    build:
      context: ./
      dockerfile: docker/Dockerfile-pandoc
    expose:
      - 80
    ports:
      - "8081:80"

    volumes:
      - pandoc-temp-datatmp:/var/www/datatmp
      - pandoc-temp-imgs:/var/www/html/imgs

    hostname: pandoc
    domainname: example.com

    restart: unless-stopped
    privileged: true
    stdin_open: false
    tty: false

  # The pandoc container does not run cron, so run cron
  # in its own container with a shared volume.
  pandoc-cron:
    build:
      context: ./
      dockerfile: docker/Dockerfile-pandoc-cron

    volumes:
      - pandoc-temp-datatmp:/var/www/datatmp
      - pandoc-temp-imgs:/var/www/html/imgs

    hostname: pandoc-cron
    domainname: example.com

    restart: unless-stopped
    privileged: true
    stdin_open: false
    tty: false

  livepoll:
    build:
      context: ./
      dockerfile: docker/Dockerfile-livepoll
    expose:
      - 80
    ports:
      - "8082:3000"

    hostname: livepoll
    domainname: example.com

    restart: unless-stopped
    privileged: true
    stdin_open: false
    tty: false

    environment:
      LIVEPOLL_USE_INSECURE_HTTP: true

volumes:
  pandoc-temp-datatmp:
  pandoc-temp-imgs:

