FROM debian:12.5

RUN apt-get update \
	&& apt-get install -y --no-install-suggests --no-install-recommends \
		cron \
	&& apt-get clean

COPY pandoc/cleanup-old-files /etc/cron.daily

RUN chmod 755 /etc/cron.daily/cleanup-old-files

CMD ["cron", "-f"]

