name: manual-deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev' 
        type: choice
        options:
        - dev
        - staging
      project:
        description: 'Project'
        required: true
        default: 'livepoll' 
        type: choice
        options:
        - livepoll
        - pandoc
jobs:
  ecs-deploy:
    name: ECS Deployment
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      project: ${{ github.event.inputs.project }}
    secrets:
      aws_user_account: ${{ secrets.AWS_USER_ACCOUNT }}
      aws_ci_account: ${{ secrets.AWS_CI_ACCOUNT }}